---

- hosts: webservers

  become: yes

  tasks:
 
  - name: Install Nginx Webserver

    apt:

      name: nginx

      state: latest

      update_cache: true
    notify:

    - start nginx

  - name: Install Php and Php-fpm in webservers
    apt: 

      name: ['php', 'php-fpm']

      update_cache:  true


      state: latest
    notify:

    - start php7.4-fpm


  - name: Copy Nginx Configuration File

    copy: dest=/etc/nginx/sites-available/default
          src=./default

  - name: Copy Php Configuration File

    copy: dest=/var/www/html/index.php
          src=./index.php

  - name: Nginx restart
    service:
      name: nginx
      state: restarted

  - name: Php7.4-fpm restart
    service:
      name: php7.4-fpm
      state: restarted

  
  
 


  handlers:

  - name: start php7.4-fpm
    service:

      name: php7.4-fpm

      state: started



  - name: start nginx
    service:

      name: nginx

      state: started


  - name: restart php7.4-fpm
    service:

      name: php7.4-fpm

      state: restarted
  - name: restart nginx

    service:

      name: nginx

      state: restarted
      
- hosts: haproxy

  become: yes

  vars:
    
    algorithm:  roundrobin

    haproxy_host_ipv4_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

  tasks:
    - name: Install HAProxy

      become: yes 
      apt: 
        name: haproxy 
        state:  present
    
    - name: Copy HAProxy Configuration File 
      template:
        src:  haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Restart HAProxy 
      service:  
        name: haproxy
        state: restarted
